export enum userRoles {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CONTENT_ADMIN = 'CONTENT_ADMIN',
  CONTENT_EDITOR = 'CONTENT_EDITOR',
  GRIEVANCE_OFFICER = 'GRIEVANCE_OFFICER',
  DEPARTMENT_ADMIN = 'DEPARTMENT_ADMIN',
  DEPARTMENT_OFFICER = 'DEPARTMENT_OFFICER',
  REPORTING_USER = 'REPORTING_USER',
}

export enum gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum templateType {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  APP_NOTIFICATION = 'APP_NOTIFICATION',
  PDF = 'PDF',
}

export enum permissions {
  READ = 'READ',
  WRITE = 'WRITE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  MANAGE = 'MANAGE',
}

export enum GrievanceCategory {
  ROAD = 'ROAD',
  WATER = 'WATER',
  SANITATION = 'SANITATION',
  ELECTRICITY = 'ELECTRICITY',
  BUILDING = 'BUILDING',
  NOISE = 'NOISE',
  DRAINAGE = 'DRAINAGE',
  STREET_LIGHT = 'STREET_LIGHT',
  GARBAGE = 'GARBAGE',
  OTHER = 'OTHER',
}

export enum GrievanceStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
}