import { DataSource } from 'typeorm';
import { CouncilMember } from '../../contacts/entities/council-member.entity';
import { OfficeContact } from '../../contacts/entities/office-contact.entity';
import { ContactsConfig } from '../../contacts/entities/contacts-config.entity';
import { EmergencyContact } from '../../contacts/entities/emergency-contact.entity';

export async function seedContacts(dataSource: DataSource): Promise<void> {
  const configRepo = dataSource.getRepository(ContactsConfig);
  const emergencyRepo = dataSource.getRepository(EmergencyContact);
  const memberRepo = dataSource.getRepository(CouncilMember);
  const contactRepo = dataSource.getRepository(OfficeContact);

  // 1. Seed Contacts Config (WhatsApp helpline + HQ)
  const configCount = await configRepo.count();
  if (configCount === 0) {
    await configRepo.save(
      configRepo.create({
        whatsappHelpline: '+91 94235 88990',
        complexName: 'Administrative Complex',
        addressLine1: 'Old Mumbai-Pune Highway, Near Kumar Resort',
        addressLine2: 'Lonavala, Dist. Pune, Maharashtra',
        pinCode: '410401',
        epabxPhones: '+91 2114 273030 / 273031 / 273032',
        officialEmail: 'contact@lonavalamc.gov.in',
        coEmail: 'co@lonavalamc.gov.in',
        workingHours: 'Monday to Saturday: 09:45 AM – 05:45 PM',
        workingHoursNote: '(Closed on 2nd & 4th Saturdays and Public Holidays)',
        mapEmbedUrl: '',
      }),
    );
    console.log('✅ Seeded Contacts Config (WhatsApp helpline & HQ)');
  }

  // 2. Seed Emergency Hotlines
  const emergencyCount = await emergencyRepo.count();
  if (emergencyCount === 0) {
    await emergencyRepo.save([
      emergencyRepo.create({
        name: '24x7 Municipal Disaster Control Room',
        number: '1800-233-0101',
        icon: 'ShieldAlert',
        category: 'emergency',
        sortOrder: 1,
        active: true,
      }),
      emergencyRepo.create({
        name: 'Lonavala Fire & Rescue Brigade',
        number: '101 / +91 2114 273101',
        icon: 'Flame',
        category: 'emergency',
        sortOrder: 2,
        active: true,
      }),
      emergencyRepo.create({
        name: 'Lonavala City Police Station',
        number: '100 / +91 2114 273033',
        icon: 'Siren',
        category: 'emergency',
        sortOrder: 3,
        active: true,
      }),
      emergencyRepo.create({
        name: 'Municipal General Ambulance & Medical',
        number: '108 / +91 2114 273111',
        icon: 'Ambulance',
        category: 'emergency',
        sortOrder: 4,
        active: true,
      }),
    ]);
    console.log('✅ Seeded 4 Emergency Hotlines');
  }

  // 3. Seed Council Members
  const memberCount = await memberRepo.count();
  if (memberCount === 0) {
    await memberRepo.save([
      memberRepo.create({
        name: 'Rajendra Babanrao Sonavane',
        marathiName: 'राजेंद्र बबनराव सोनावणे',
        designation: 'President, Lonavla Municipal Council',
        roleCategory: 'President',
        ward: 'Municipal Council',
        tenure: '2022 - 2027',
        committee: 'Standing Committee',
        phone: '9422350846',
        email: 'sonavanerajendra1961@gmail.com',
        address: 'Lonavla Municipal Council, Lonavala - 410401',
        imageUrl:
          'https://res.cloudinary.com/mpo7ijbf/image/upload/v1789642075/lonavala/council/Rajendra_Sonavane__President__1789642073359.jpg',
        message: '',
        sortOrder: 1,
        active: true,
      }),
      memberRepo.create({
        name: 'Devidas Bhausaheb Kadu',
        marathiName: 'देवीदास भाऊसाहेब कडू',
        designation: 'Vicepresident, Lonavla Municipal Council',
        roleCategory: 'Vice President',
        ward: 'Municipal Council',
        tenure: '2022 - 2027',
        committee: null,
        phone: '7798777077',
        email: 'deva7077@gmail.com',
        address: 'Lonavla Municipal Council, Lonavala - 410401',
        imageUrl:
          'https://res.cloudinary.com/mpo7ijbf/image/upload/v1789642098/lonavala/council/Devidas_Kadu_-_Vicepresident__1789642095196.jpg',
        message: '',
        sortOrder: 2,
        active: true,
      }),
      memberRepo.create({
        name: 'Sunny Ram Dalvi',
        marathiName: 'सनी राम दालवी',
        designation: 'Chairman, Public Works Committee',
        roleCategory: 'Corporator',
        ward: 'Ward 1',
        tenure: '2022 - 2027',
        committee: 'Public Works Committee',
        phone: '9923103509',
        email: 'concept01con@gmail.com',
        address: 'Ward 1, Lonavala - 410401',
        imageUrl:
          'https://res.cloudinary.com/mpo7ijbf/image/upload/v1789642216/lonavala/council/Sunny_Dalvi_1789642214780.jpg',
        message: '',
        sortOrder: 3,
        active: true,
      }),
      memberRepo.create({
        name: 'Deepa Mangeysh Agarrwal',
        marathiName: 'दीपा मंगेश अग्रवाल',
        designation: 'Chairman, Education Committee',
        roleCategory: 'Corporator',
        ward: 'Ward 8',
        tenure: '2022 - 2027',
        committee: 'Education Committee',
        phone: '9890346149',
        email: 'mangeyshagarrwal@yahoo.com',
        address: 'Ward 8, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 4,
        active: true,
      }),
      memberRepo.create({
        name: 'Dhananjay Vasant Kalokhe',
        marathiName: 'धनंजय वसंत काळोखे',
        designation: 'Chairman, Sanitation, Medical and Public Health Committee',
        roleCategory: 'Corporator',
        ward: 'Ward 13',
        tenure: '2022 - 2027',
        committee: 'Sanitation, Medical and Public Health Committee',
        phone: '9604007770',
        email: 'dhananjaykalokhe@gmail.com',
        address: 'Ward 13, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 5,
        active: true,
      }),
      memberRepo.create({
        name: 'Jeevan Prakash Gaikwad',
        marathiName: 'जीवन प्रकाश गायकवाड',
        designation: 'Chairman, Water Supply and Drainage Committee',
        roleCategory: 'Corporator',
        ward: 'Ward 11',
        tenure: '2022 - 2027',
        committee: 'Water Supply and Drainage Committee',
        phone: '9850761414',
        email: 'jeevangaikwad26@gmail.com',
        address: 'Ward 11, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 6,
        active: true,
      }),
      memberRepo.create({
        name: 'Swapna Atul Kadam',
        marathiName: 'स्वप्ना अतुल कदम',
        designation: 'Chairman, Women and Child Welfare Committee',
        roleCategory: 'Corporator',
        ward: 'Ward 12',
        tenure: '2022 - 2027',
        committee: 'Women and Child Welfare Committee',
        phone: '9049802848',
        email: 'atulkadam4848@gmail.com',
        address: 'Ward 12, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 7,
        active: true,
      }),
      memberRepo.create({
        name: 'Bhagyashri Mahadev Jagtap',
        marathiName: 'भाग्यश्री महादेव जगताप',
        designation: 'Vicechairman, Women and Child Welfare Committee',
        roleCategory: 'Corporator',
        ward: 'Ward 11',
        tenure: '2022 - 2027',
        committee: 'Women and Child Welfare Committee',
        phone: '7264873703',
        email: 'mahadevjagtap08@gmail.com',
        address: 'Ward 11, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 8,
        active: true,
      }),
      memberRepo.create({
        name: 'Mangesh Dattatraya Mavakar',
        marathiName: 'मंगेश दत्तात्रय मावकर',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 2',
        tenure: '2022 - 2027',
        committee: null,
        phone: '8432771111',
        email: 'mangeshmavkar1984@gmail.com',
        address: 'Ward 2, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 9,
        active: true,
      }),
      memberRepo.create({
        name: 'Sana Raju Chowdhary',
        marathiName: 'सना राजू चौधरी',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 1',
        tenure: '2022 - 2027',
        committee: null,
        phone: '8007176549',
        email: 'sanaprathm@gmail.com',
        address: 'Ward 1, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 10,
        active: true,
      }),
      memberRepo.create({
        name: 'Anita Sandip Ambure',
        marathiName: 'अनिता संदीप अंबुरे',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 2',
        tenure: '2022 - 2027',
        committee: null,
        phone: '8390563569',
        email: 'ambureanu@gmail.com',
        address: 'Ward 2, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 11,
        active: true,
      }),
      memberRepo.create({
        name: 'Shweta Chandrakant Gaikwad',
        marathiName: 'श्वेता चंद्रकांत गायकवाड',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 3',
        tenure: '2022 - 2027',
        committee: null,
        phone: '7798239068',
        email: 'gaikwadshweta999@gmail.com',
        address: 'Ward 3, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 12,
        active: true,
      }),
      memberRepo.create({
        name: 'Laxmi Narayan Palekar',
        marathiName: 'लक्ष्मी नारायण पालेकर',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 3',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9823677999',
        email: 'laxminpalekar77999@gmail.com',
        address: 'Ward 3, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 13,
        active: true,
      }),
      memberRepo.create({
        name: 'Gayatri Dharmesh Rile',
        marathiName: 'गायत्री धर्मेश रिले',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 4',
        tenure: '2022 - 2027',
        committee: null,
        phone: '8412096102',
        email: 'rilegayatri@gmail.com',
        address: 'Ward 4, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 14,
        active: true,
      }),
      memberRepo.create({
        name: 'Usha Ashok Chowdhary',
        marathiName: 'उषा अशोक चौधरी',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 4',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9511111363',
        email: 'ushaachowdhary@gmail.com',
        address: 'Ward 4, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 15,
        active: true,
      }),
      memberRepo.create({
        name: 'Vasundhara Nitin Durge',
        marathiName: 'वसुंधरा नितीन दुर्गे',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 5',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9765187486',
        email: 'samrudhi.d1976@gmail.com',
        address: 'Ward 5, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 16,
        active: true,
      }),
      memberRepo.create({
        name: 'Subhash Sumant Denkar',
        marathiName: 'सुभाष सुमंत डेंकर',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 5',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9960387175',
        email: 'denkarsubhash@gmail.com',
        address: 'Ward 5, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 17,
        active: true,
      }),
      memberRepo.create({
        name: 'Reshma Arjun Pathare',
        marathiName: 'रेश्मा अर्जुन पठारे',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 6',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9545160797',
        email: 'pathare.reshma@rediffmail.com',
        address: 'Ward 6, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 18,
        active: true,
      }),
      memberRepo.create({
        name: 'Dattatray Ramchandra Yeole',
        marathiName: 'दत्तात्रय रामचंद्र येवले',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 6',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9823042004',
        email: 'aesthetic.planners@gmail.com',
        address: 'Ward 6, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 19,
        active: true,
      }),
      memberRepo.create({
        name: 'Arti Maruti Tikone',
        marathiName: 'आरती मारुती टिकोने',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 7',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9673898979',
        email: 'nikhiltikone555@gmail.com',
        address: 'Ward 7, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 20,
        active: true,
      }),
      memberRepo.create({
        name: 'Sunny Pandurang Ghone',
        marathiName: 'सनी पांडुरंग घोणे',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 8',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9822645288',
        email: '123sunnyghone123@gmail.com',
        address: 'Ward 8, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 21,
        active: true,
      }),
      memberRepo.create({
        name: 'Nayna Yogesh Pailkar',
        marathiName: 'नयना योगेश पाईळकर',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 9',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9763042873',
        email: 'naynapailkar07@gmail.com',
        address: 'Ward 9, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 22,
        active: true,
      }),
      memberRepo.create({
        name: 'Mubin Nazir Inamdar',
        marathiName: 'मुबीन नजीर इनामदार',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 9',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9922337868',
        email: 'inamdarsons09@gmail.com',
        address: 'Ward 9, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 23,
        active: true,
      }),
      memberRepo.create({
        name: 'Vaishali Sunil Mogare',
        marathiName: 'वैशाली सुनील मोगरे',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 10',
        tenure: '2022 - 2027',
        committee: null,
        phone: '8551015733',
        email: 'kaushikm1307@gmail.com',
        address: 'Ward 10, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 24,
        active: true,
      }),
      memberRepo.create({
        name: 'Anil Mahadeo Gawali',
        marathiName: 'अनिल महादेव गवळी',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 10',
        tenure: '2022 - 2027',
        committee: null,
        phone: '8806141628',
        email: 'aanilgawli99@gmail.com',
        address: 'Ward 10, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 25,
        active: true,
      }),
      memberRepo.create({
        name: 'Sumit Prakash Gawali',
        marathiName: 'सुमित प्रकाश गवळी',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 12',
        tenure: '2022 - 2027',
        committee: null,
        phone: '8263967261',
        email: 'sumitgawali1984@gmail.com',
        address: 'Ward 12, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 26,
        active: true,
      }),
      memberRepo.create({
        name: 'Priyanka Kishor Konde',
        marathiName: 'प्रियांका किशोर कोंडे',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 13',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9545923023',
        email: 'piyukonde09@gmail.com',
        address: 'Ward 13, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 27,
        active: true,
      }),
      memberRepo.create({
        name: 'Sonali Sambhaji Marathe',
        marathiName: 'सोनाली संभाजी मराठे',
        designation: 'Councillor',
        roleCategory: 'Corporator',
        ward: 'Ward 13',
        tenure: '2022 - 2027',
        committee: null,
        phone: '7387821207',
        email: 'sonalim4874@gmail.com',
        address: 'Ward 13, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 28,
        active: true,
      }),
      memberRepo.create({
        name: 'Mukesh Thanmal Parmar',
        marathiName: 'मुकेश थानमल परमार',
        designation: 'Nominated Councillor',
        roleCategory: 'Nominated',
        ward: 'Municipal Council',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9890401613',
        email: '',
        address: 'Lonavala Municipal Council, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 29,
        active: true,
      }),
      memberRepo.create({
        name: 'Nikhil Dhananjay Kavishwar',
        marathiName: 'निखिल धनंजय कवीश्वर',
        designation: 'Nominated Councillor',
        roleCategory: 'Nominated',
        ward: 'Municipal Council',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9822778970',
        email: '',
        address: 'Lonavala Municipal Council, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 30,
        active: true,
      }),
      memberRepo.create({
        name: 'Mahammad Zakir Ayub Khalifa',
        marathiName: 'महंमद झाकीर अयुब खलिफा',
        designation: 'Nominated Councillor',
        roleCategory: 'Nominated',
        ward: 'Municipal Council',
        tenure: '2022 - 2027',
        committee: null,
        phone: '9372089113',
        email: '',
        address: 'Lonavala Municipal Council, Lonavala - 410401',
        imageUrl: '',
        message: '',
        sortOrder: 31,
        active: true,
      }),
    ]);
    console.log('✅ Seeded 31 Council Members');
  }

  // 4. Seed Office Contacts
  const contactCount = await contactRepo.count();
  if (contactCount === 0) {
    await contactRepo.save([
      contactRepo.create({
        title: '24x7 Municipal Disaster Control Room',
        phone: '1800-233-0101',
        altPhone: '+91 2114 273030',
        email: 'controlroom@lonavalamc.gov.in',
        location: 'Ground Floor, LMC Administrative Complex',
        timing: '24 Hours / 7 Days a Week',
        category: 'emergency',
        sortOrder: 1,
        active: true,
      }),
      contactRepo.create({
        title: 'Lonavala Fire & Rescue Brigade',
        phone: '101',
        altPhone: '+91 2114 273101',
        email: 'fire@lonavalamc.gov.in',
        location: 'Fire Station, Near Kumar Resort, Old Highway',
        timing: '24x7 Emergency Response',
        category: 'emergency',
        sortOrder: 2,
        active: true,
      }),
      contactRepo.create({
        title: 'Municipal General Dispensary & Ambulance',
        phone: '108',
        altPhone: '+91 2114 273111',
        email: 'health@lonavalamc.gov.in',
        location: 'Municipal Health Center, Gawli Wada Road',
        timing: '24 Hours Emergency Care',
        category: 'emergency',
        sortOrder: 3,
        active: true,
      }),
      contactRepo.create({
        title: 'Citizen Facilitation Center (CFC Helpdesk)',
        phone: '+91 2114 273035',
        email: 'helpdesk@lonavalamc.gov.in',
        location: 'LMC Administrative Complex, Lonavala',
        timing: '10:00 AM – 5:30 PM (Mon to Sat)',
        category: 'administrative',
        sortOrder: 4,
        active: true,
      }),
    ]);
    console.log('✅ Seeded 4 Office & Department Contacts');
  }
}
