import { DataSource } from 'typeorm';
import { CouncilMember } from '../../contacts/entities/council-member.entity';
import { OfficeContact } from '../../contacts/entities/office-contact.entity';

export async function seedContacts(dataSource: DataSource): Promise<void> {
  const memberRepo = dataSource.getRepository(CouncilMember);
  const contactRepo = dataSource.getRepository(OfficeContact);

  // Clear existing council members to ensure accurate latest data
  await memberRepo.clear();

  const membersData = [
    {
      name: 'Rajendra Babanrao Sonavane',
      marathiName: 'राजेंद्र बबनराव सोनवणे',
      designation: 'President, Lonavla Municipal Council',
      roleCategory: 'President',
      ward: 'Central / All Wards',
      tenure: 'Current Term',
      committee: 'General Body & Standing Committee',
      phone: '+91 94223 50846',
      email: 'sonavanerajendra1961@gmail.com',
      address: 'Lonavla Municipal Council Administrative Complex',
      imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
      sortOrder: 1,
      active: true,
    },
    {
      name: 'Devidas Bhausaheb Kadu',
      marathiName: 'देवीदास भाऊसाहेब कडू',
      designation: 'Vicepresident, Lonavla Municipal Council',
      roleCategory: 'Vice President',
      ward: 'Central / All Wards',
      tenure: 'Current Term',
      committee: 'Public Works & Administration',
      phone: '+91 77987 77077',
      email: 'deva7077@gmail.com',
      address: 'Lonavla Municipal Council Administrative Complex',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      sortOrder: 2,
      active: true,
    },
    {
      name: 'Sunny Ram Dalvi',
      marathiName: 'सन्नी राम दालवी',
      designation: 'Chairman, Public Works Committee',
      roleCategory: 'Committee Chairman',
      ward: 'Ward 1',
      tenure: 'Current Term',
      committee: 'Public Works Committee',
      phone: '+91 99231 03509',
      email: 'concept01con@gmail.com',
      address: 'Ward 1, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
      sortOrder: 3,
      active: true,
    },
    {
      name: 'Deepa Mangeysh Agarrwal',
      marathiName: 'दीपा मंगेश अगरवाल',
      designation: 'Chairman, Education Committee',
      roleCategory: 'Committee Chairman',
      ward: 'Ward 8',
      tenure: 'Current Term',
      committee: 'Education Committee',
      phone: '+91 98903 46149',
      email: 'mangeyshagarrwal@yahoo.com',
      address: 'Ward 8, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
      sortOrder: 4,
      active: true,
    },
    {
      name: 'Dhananjay Vasant Kalokhe',
      marathiName: 'धनंजय वसंत काळोखे',
      designation: 'Chairman, Sanitation, Medical and Public Health Committee',
      roleCategory: 'Committee Chairman',
      ward: 'Ward 13',
      tenure: 'Current Term',
      committee: 'Sanitation, Medical and Public Health Committee',
      phone: '+91 96040 07770',
      email: 'dhananjaykalokhe@gmail.com',
      address: 'Ward 13, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
      sortOrder: 5,
      active: true,
    },
    {
      name: 'Jeevan Prakash Gaikwad',
      marathiName: 'जीवन प्रकाश गायकवाड',
      designation: 'Chairman, Water Supply and Drainage Committee',
      roleCategory: 'Committee Chairman',
      ward: 'Ward 11',
      tenure: 'Current Term',
      committee: 'Water Supply and Drainage Committee',
      phone: '+91 98507 61414',
      email: 'jeevangaikwad26@gmail.com',
      address: 'Ward 11, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
      sortOrder: 6,
      active: true,
    },
    {
      name: 'Swapna Atul Kadam',
      marathiName: 'स्वप्ना अतुल कदम',
      designation: 'Chairman, Women and Child Welfare Committee',
      roleCategory: 'Committee Chairman',
      ward: 'Ward 12',
      tenure: 'Current Term',
      committee: 'Women and Child Welfare Committee',
      phone: '+91 90498 02848',
      email: 'atulkadam4848@gmail.com',
      address: 'Ward 12, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
      sortOrder: 7,
      active: true,
    },
    {
      name: 'Bhagyashri Mahadev Jagtap',
      marathiName: 'भाग्यश्री महादेव जगताप',
      designation: 'Vicechairman, Women and Child Welfare Committee',
      roleCategory: 'Committee Chairman',
      ward: 'Ward 11',
      tenure: 'Current Term',
      committee: 'Women and Child Welfare Committee',
      phone: '+91 72648 73703',
      email: 'mahadevjagtap08@gmail.com',
      address: 'Ward 11, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=600&q=80',
      sortOrder: 8,
      active: true,
    },
    {
      name: 'Mangesh Dattatraya Mavakar',
      marathiName: 'मंगेश दत्तात्रय मावकर',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 2',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 84327 71111',
      email: 'mangeshmavkar1984@gmail.com',
      address: 'Ward 2, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
      sortOrder: 9,
      active: true,
    },
    {
      name: 'Sana Raju Chowdhary',
      marathiName: 'सना राजू चौधरी',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 1',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 80071 76549',
      email: 'sanaprathm@gmail.com',
      address: 'Ward 1, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      sortOrder: 10,
      active: true,
    },
    {
      name: 'Anita Sandip Ambure',
      marathiName: 'अनिता संदीप अंबुरे',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 2',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 83905 63569',
      email: 'ambureanu@gmail.com',
      address: 'Ward 2, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
      sortOrder: 11,
      active: true,
    },
    {
      name: 'Shweta Chandrakant Gaikwad',
      marathiName: 'श्वेता चंद्रकांत गायकवाड',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 3',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 77982 39068',
      email: 'gaikwadshweta999@gmail.com',
      address: 'Ward 3, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      sortOrder: 12,
      active: true,
    },
    {
      name: 'Laxmi Narayan Palekar',
      marathiName: 'लक्ष्मी नारायण पालेकर',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 3',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 98236 77999',
      email: 'laxminpalekar77999@gmail.com',
      address: 'Ward 3, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
      sortOrder: 13,
      active: true,
    },
    {
      name: 'Gayatri Dharmesh Rile',
      marathiName: 'गायत्री धर्मेश रिले',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 4',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 84120 96102',
      email: 'rilegayatri@gmail.com',
      address: 'Ward 4, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
      sortOrder: 14,
      active: true,
    },
    {
      name: 'Usha Ashok Chowdhary',
      marathiName: 'उषा अशोक चौधरी',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 4',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 95111 11363',
      email: 'ushaachowdhary@gmail.com',
      address: 'Ward 4, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=600&q=80',
      sortOrder: 15,
      active: true,
    },
    {
      name: 'Vasundhara Nitin Durge',
      marathiName: 'वसुंधरा नितीन दुर्गे',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 5',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 97651 87486',
      email: 'samrudhi.d1976@gmail.com',
      address: 'Ward 5, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&q=80',
      sortOrder: 16,
      active: true,
    },
    {
      name: 'Subhash Sumant Denkar',
      marathiName: 'सुभाष सुमंत डेंकर',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 5',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 99603 87175',
      email: 'denkarsubhash@gmail.com',
      address: 'Ward 5, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
      sortOrder: 17,
      active: true,
    },
    {
      name: 'Reshma Arjun Pathare',
      marathiName: 'रेश्मा अर्जुन पठारे',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 6',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 95451 60797',
      email: 'pathare.reshma@rediffmail.com',
      address: 'Ward 6, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=600&q=80',
      sortOrder: 18,
      active: true,
    },
    {
      name: 'Dattatray Ramchandra Yeole',
      marathiName: 'दत्तात्रय रामचंद्र येवले',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 6',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 98230 42004',
      email: 'aesthetic.planners@gmail.com',
      address: 'Ward 6, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
      sortOrder: 19,
      active: true,
    },
    {
      name: 'Arti Maruti Tikone',
      marathiName: 'आरती मारुती टिकोने',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 7',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 96738 98979',
      email: 'nikhiltikone555@gmail.com',
      address: 'Ward 7, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      sortOrder: 20,
      active: true,
    },
    {
      name: 'Sunny Pandurang Ghone',
      marathiName: 'सन्नी पांडुरंग घोणे',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 8',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 98226 45288',
      email: '123sunnyghone123@gmail.com',
      address: 'Ward 8, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
      sortOrder: 21,
      active: true,
    },
    {
      name: 'Nayna Yogesh Pailkar',
      marathiName: 'नयना योगेश पाईलकर',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 9',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 97630 42873',
      email: 'naynapailkar07@gmail.com',
      address: 'Ward 9, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      sortOrder: 22,
      active: true,
    },
    {
      name: 'Mubin Nazir Inamdar',
      marathiName: 'मुबीन नजीर इनामदार',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 9',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 99223 37868',
      email: 'inamdarsons09@gmail.com',
      address: 'Ward 9, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      sortOrder: 23,
      active: true,
    },
    {
      name: 'Vaishali Sunil Mogare',
      marathiName: 'वैशाली सुनील मोगरे',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 10',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 85510 15733',
      email: 'kaushikm1307@gmail.com',
      address: 'Ward 10, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
      sortOrder: 24,
      active: true,
    },
    {
      name: 'Anil Mahadeo Gawali',
      marathiName: 'अनिल महादेव गवळी',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 10',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 88061 41628',
      email: 'aanilgawli99@gmail.com',
      address: 'Ward 10, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
      sortOrder: 25,
      active: true,
    },
    {
      name: 'Sumit Prakash Gawali',
      marathiName: 'सुमित प्रकाश गवळी',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 12',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 82639 67261',
      email: 'sumitgawali1984@gmail.com',
      address: 'Ward 12, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
      sortOrder: 26,
      active: true,
    },
    {
      name: 'Priyanka Kishor Konde',
      marathiName: 'प्रियांका किशोर कोंडे',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 13',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 95459 23023',
      email: 'piyukonde09@gmail.com',
      address: 'Ward 13, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
      sortOrder: 27,
      active: true,
    },
    {
      name: 'Sonali Sambhaji Marathe',
      marathiName: 'सोनाली संभाजी मराठे',
      designation: 'Councillor',
      roleCategory: 'Councillor',
      ward: 'Ward 13',
      tenure: 'Current Term',
      committee: 'Municipal Council',
      phone: '+91 73878 21207',
      email: 'sonalim4874@gmail.com',
      address: 'Ward 13, Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
      sortOrder: 28,
      active: true,
    },
    {
      name: 'Mukesh Thanmal Parmar',
      marathiName: 'मुकेश थानमल परमार',
      designation: 'Nominated Councillor',
      roleCategory: 'Nominated Councillor',
      ward: 'Nominated',
      tenure: 'Current Term',
      committee: 'Nominated Member',
      phone: '+91 98904 01613',
      email: 'mukeshparmar@lonavalamc.gov.in',
      address: 'Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
      sortOrder: 29,
      active: true,
    },
    {
      name: 'Nikhil Dhananjay Kavishwar',
      marathiName: 'निखिल धनंजय कवीश्वर',
      designation: 'Nominated Councillor',
      roleCategory: 'Nominated Councillor',
      ward: 'Nominated',
      tenure: 'Current Term',
      committee: 'Nominated Member',
      phone: '+91 98227 78970',
      email: 'nikhilkavishwar@lonavalamc.gov.in',
      address: 'Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
      sortOrder: 30,
      active: true,
    },
    {
      name: 'Mahammad Zakir Ayub Khalifa',
      marathiName: 'मोहम्मद झाकीर अयुब खलिफा',
      designation: 'Nominated Councillor',
      roleCategory: 'Nominated Councillor',
      ward: 'Nominated',
      tenure: 'Current Term',
      committee: 'Nominated Member',
      phone: '+91 93720 89113',
      email: 'zakirkhalifa@lonavalamc.gov.in',
      address: 'Lonavla',
      imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
      sortOrder: 31,
      active: true,
    },
  ];

  const entities = membersData.map((data) => memberRepo.create(data));
  await memberRepo.save(entities);
  console.log(`✅ Seeded ${entities.length} Council Members with verified latest roster`);

  const contactCount = await contactRepo.count();
  if (contactCount === 0) {
    await contactRepo.save([
      contactRepo.create({
        title: '24x7 Municipal Disaster Control Room',
        phone: '1800-233-0101',
        altPhone: '+91 2114 273030',
        email: 'controlroom@lonavalamc.gov.in',
        location: 'Ground Floor, LMC Administrative Complex',
        timing: '24 Hours / 7 Days a Week',
        category: 'emergency',
        sortOrder: 1,
        active: true,
      }),
      contactRepo.create({
        title: 'Lonavala Fire & Rescue Brigade',
        phone: '101',
        altPhone: '+91 2114 273101',
        email: 'fire@lonavalamc.gov.in',
        location: 'Fire Station, Near Kumar Resort, Old Highway',
        timing: '24x7 Emergency Response',
        category: 'emergency',
        sortOrder: 2,
        active: true,
      }),
      contactRepo.create({
        title: 'Municipal General Dispensary & Ambulance',
        phone: '108',
        altPhone: '+91 2114 273111',
        email: 'health@lonavalamc.gov.in',
        location: 'Municipal Health Center, Gawli Wada Road',
        timing: '24 Hours Emergency Care',
        category: 'emergency',
        sortOrder: 3,
        active: true,
      }),
      contactRepo.create({
        title: 'Citizen Facilitation Center (CFC Helpdesk)',
        phone: '+91 2114 273035',
        email: 'helpdesk@lonavalamc.gov.in',
        location: 'LMC Administrative Complex, Lonavala',
        timing: '10:00 AM – 5:30 PM (Mon to Sat)',
        category: 'administrative',
        sortOrder: 4,
        active: true,
      }),
    ]);
    console.log('✅ Seeded 4 Office & Emergency Contacts');
  }
}
