import { DataSource } from 'typeorm';
import { CourtCommitteeMemberEntity } from '../../court-member/entities/court-member.entity';

export const DEFAULT_COURT_MEMBERS_DATA: Partial<CourtCommitteeMemberEntity>[] = [
  {
    name: 'Adv. Rajesh V. Deshmukh',
    marathiName: 'अ‍ॅड. राजेश वि. देशमुख',
    designation: 'Chairman, Legal & Law Committee (सभापती, विधी व न्याय समिती)',
    role: 'Chairman',
    category: 'Leadership',
    phone: '+91 2114 273201',
    email: 'legal.chair@lonavalacouncil.gov.in',
    ward: 'Ward 04 - Ryewood',
    experience: '18+ years in Municipal Law & Civil Jurisprudence',
    image: '',
    responsibilities: [
      'Presiding over municipal legal review meetings and statutory policy framing',
      'Evaluating legal claims, writ petitions, and high-value contractual disputes',
      'Sanctioning appeals and revisions before the Hon\'ble High Court of Bombay',
      'Supervising Lok Adalat compromise settlements for public revenue',
    ],
    sortOrder: 1,
    active: true,
  },
  {
    name: 'Smt. Sunita Kishor Pawar',
    marathiName: 'श्रीमती सुनिता किशोर पवार',
    designation: 'Vice Chairperson & Corporator (उपसभापती व नगरसेविका)',
    role: 'Vice Chairperson',
    category: 'Leadership',
    phone: '+91 2114 273202',
    email: 'sunita.pawar@lonavalacouncil.gov.in',
    ward: 'Ward 09 - Bhangarwadi',
    experience: '10+ years public service & consumer arbitration',
    image: '',
    responsibilities: [
      'Review of public grievances under statutory municipal provisions',
      'Coordination with Women & Child cell on legal aid and awareness',
      'Monitoring municipal encroachment dispute resolutions',
    ],
    sortOrder: 2,
    active: true,
  },
  {
    name: 'Adv. (Dr.) Dilip R. Patil',
    marathiName: 'अ‍ॅड. (डॉ.) दिलीप आर. पाटील',
    designation: 'Chief Legal Advisor & Former District Judge (मुख्य कायदेशीर सल्लागार)',
    role: 'Chief Legal Advisor',
    category: 'Leadership',
    phone: '+91 2114 273206',
    email: 'dilip.patil.legal@lonavalacouncil.gov.in',
    ward: 'Appointed Judicial Expert',
    experience: '28+ years judicial & legal consulting experience',
    image: '',
    responsibilities: [
      'Senior counsel to President & Chief Officer on constitutional matters',
      'Review of town planning bylaws and development control regulations',
      'Guidance on high-stakes arbitration and infrastructure contract litigations',
    ],
    sortOrder: 3,
    active: true,
  },
  {
    name: 'Shri. Mahendra G. Shinde',
    marathiName: 'श्री. महेंद्र गो. शिंदे',
    designation: 'Committee Member & Corporator (समिती सदस्य व नगरसेवक)',
    role: 'Member',
    category: 'Committee Member',
    phone: '+91 2114 273204',
    email: 'mahendra.shinde@lonavalacouncil.gov.in',
    ward: 'Ward 12 - Valvan',
    experience: '8 years municipal governance',
    image: '',
    responsibilities: [
      'Review of town planning and building permission litigations',
      'Public property boundary demarcation and title verification oversight',
    ],
    sortOrder: 4,
    active: true,
  },
  {
    name: 'Smt. Kavita Nitin Gaikwad',
    marathiName: 'श्रीमती कविता नितीन गायकवाड',
    designation: 'Committee Member & Corporator (समिती सदस्य व नगरसेविका)',
    role: 'Member',
    category: 'Committee Member',
    phone: '+91 2114 273211',
    email: 'kavita.gaikwad@lonavalacouncil.gov.in',
    ward: 'Ward 07 - Gavthan',
    experience: '6 years civic governance',
    image: '',
    responsibilities: [
      'Ward-level public dispute conciliation and grievance coordination',
      'Monitoring municipal property lease agreements and rent recovery cases',
    ],
    sortOrder: 5,
    active: true,
  },
  {
    name: 'Shri. Sandeep B. Kadam',
    marathiName: 'श्री. संदीप बा. कदम',
    designation: 'Committee Member & Corporator (समिती सदस्य व नगरसेवक)',
    role: 'Member',
    category: 'Committee Member',
    phone: '+91 2114 273212',
    email: 'sandeep.kadam@lonavalacouncil.gov.in',
    ward: 'Ward 02 - Khandala',
    experience: '9 years public representation',
    image: '',
    responsibilities: [
      'Oversight of public works contractual disputes and tender compliance',
      'Liaison with Khandala ward citizens for Lok Adalat camps',
    ],
    sortOrder: 6,
    active: true,
  },
  {
    name: 'Smt. Pratibha Arvind More',
    marathiName: 'श्रीमती प्रतिभा अरविंद मोरे',
    designation: 'Committee Member & Corporator (समिती सदस्य व नगरसेविका)',
    role: 'Member',
    category: 'Committee Member',
    phone: '+91 2114 273213',
    email: 'pratibha.more@lonavalacouncil.gov.in',
    ward: 'Ward 05 - Thombrewadi',
    experience: '5 years civic administration',
    image: '',
    responsibilities: [
      'Civic amenity dispute redressal and slum regularization legal reviews',
      'Coordination of citizen legal awareness camps in rural/fringe wards',
    ],
    sortOrder: 7,
    active: true,
  },
  {
    name: 'Shri. Deepak S. Sanas',
    marathiName: 'श्री. दीपक एस. सणस',
    designation: 'Committee Member & Corporator (समिती सदस्य व नगरसेवक)',
    role: 'Member',
    category: 'Committee Member',
    phone: '+91 2114 273214',
    email: 'deepak.sanas@lonavalacouncil.gov.in',
    ward: 'Ward 11 - Varsoli',
    experience: '7 years local governance',
    image: '',
    responsibilities: [
      'Water pipeline corridor right-of-way and road widening litigation review',
      'Scrutiny of commercial hoarding violations and compounding appeals',
    ],
    sortOrder: 8,
    active: true,
  },
  {
    name: 'Smt. Rekha Vilas Kamble',
    marathiName: 'श्रीमती रेखा विलास कांबळे',
    designation: 'Committee Member & Corporator (समिती सदस्य व नगरसेविका)',
    role: 'Member',
    category: 'Committee Member',
    phone: '+91 2114 273215',
    email: 'rekha.kamble@lonavalacouncil.gov.in',
    ward: 'Ward 15 - Nangargaon',
    experience: '11 years public leadership',
    image: '',
    responsibilities: [
      'Solid waste management compliance under Environmental Protection Act',
      'Public health bylaw enforcement litigations oversight',
    ],
    sortOrder: 9,
    active: true,
  },
  {
    name: 'Shri. Amit Sudhakar Jadhav',
    marathiName: 'श्री. अमित सुधाकर जाधव',
    designation: 'Chief Legal Officer & Secretary (मुख्य विधी सल्लागार व सचिव)',
    role: 'Chief Legal Officer',
    category: 'Legal Officer',
    phone: '+91 2114 273203',
    email: 'law.officer@lonavalacouncil.gov.in',
    ward: 'LMC Administrative Headquarters',
    experience: 'LL.M. (Constitutional Law), 14 years judicial liaison experience',
    image: '',
    responsibilities: [
      'Scrutinizing statutory notices under Sec. 304 of MMC Act 1965',
      'Drafting written statements, counter affidavits, and caveat petitions',
      'Liaison with empanelled advocates across High Court & Sub-Divisional courts',
      'Supervision of the Council\'s Law Branch records & digital cause lists',
    ],
    sortOrder: 10,
    active: true,
  },
  {
    name: 'Adv. Snehal A. Kulkarni',
    marathiName: 'अ‍ॅड. स्नेहल अ. कुलकर्णी',
    designation: 'Legal Consultant - Environmental Law (पर्यावरण विधी सल्लागार)',
    role: 'Special Invitee Consultant',
    category: 'Legal Officer',
    phone: '+91 2114 273205',
    email: 'snehal.kulkarni@lonavalacouncil.gov.in',
    ward: 'Empanelled Expert',
    experience: '12 years in Environmental Law & NGT Western Zone matters',
    image: '',
    responsibilities: [
      'Guiding council on National Green Tribunal and eco-sensitive zone compliances',
      'Assisting in drafting town planning bylaws and civic standard operating procedures',
    ],
    sortOrder: 11,
    active: true,
  },
  {
    name: 'Shri. Nilesh M. Joshi',
    marathiName: 'श्री. निलेश म. जोशी',
    designation: 'Assistant Law Officer (सहाय्यक विधी अधिकारी)',
    role: 'Assistant Law Officer',
    category: 'Legal Officer',
    phone: '+91 2114 273216',
    email: 'nilesh.joshi@lonavalacouncil.gov.in',
    ward: 'Legal Department, 2nd Floor',
    experience: 'B.S.L., LL.B., 7 years municipal law practice',
    image: '',
    responsibilities: [
      'Managing court hearing dates, brief preparations, and evidence documents',
      'Coordination with town planning engineers for site panchnama and stay reports',
      'Drafting RTI second appeal responses before State Information Commission',
    ],
    sortOrder: 12,
    active: true,
  },
  {
    name: 'Adv. Rameshwar K. Joshi',
    marathiName: 'अ‍ॅड. रामेश्वर के. जोशी',
    designation: 'Senior Conciliator - Lok Adalat Panel (ज्येष्ठ तडजोडकार)',
    role: 'Panel Conciliator',
    category: 'Committee Member',
    phone: '+91 2114 273217',
    email: 'rameshwar.joshi@lonavalacouncil.gov.in',
    ward: 'Lok Adalat Bench Room',
    experience: '22 years civil mediation & arbitration',
    image: '',
    responsibilities: [
      'Presiding as municipal panel mediator for property tax compromise cases',
      'Evaluating compounding fine reductions under state government schemes',
    ],
    sortOrder: 13,
    active: true,
  },
  {
    name: 'Adv. Anjali P. Kulkarni',
    marathiName: 'अ‍ॅड. अंजली पी. कुलकर्णी',
    designation: 'Legal Aid Counselor - Public Redressal (विधी सहाय्य सल्लागार)',
    role: 'Legal Aid Counselor',
    category: 'Committee Member',
    phone: '+91 2114 273218',
    email: 'anjali.kulkarni@lonavalacouncil.gov.in',
    ward: 'Citizen Facilitation Center',
    experience: '13 years family & civic legal counseling',
    image: '',
    responsibilities: [
      'Providing free initial legal guidance to senior citizens and low-income residents',
      'Assisting citizens in drafting Lok Adalat compromise applications',
    ],
    sortOrder: 14,
    active: true,
  },
];

export async function seedCourtMembers(dataSource: DataSource): Promise<void> {
  const memberRepo = dataSource.getRepository(CourtCommitteeMemberEntity);
  const count = await memberRepo.count();

  if (count === 0) {
    const entities = memberRepo.create(DEFAULT_COURT_MEMBERS_DATA);
    await memberRepo.save(entities);
    console.log(`✅ Seeded ${entities.length} Court Committee Members into database`);
  } else {
    console.log(`ℹ️ Court Committee Members already exist (${count} found), skipping seed`);
  }
}
